deploymentMode: SelectorSyncSet
selectorSyncSet:
  matchExpressions:
    - key: ext-hypershift.openshiftio/cluster-type
      operator: In
      values: ["management-cluster"]
    - key: api.openshift.com/fedramp
      operator: NotIn
      values: ["true"]
