---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: audit-webhook
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - splunkforwarder
  resources:
  - securitycontextconstraints
  verbs:
  - use
