---
apiVersion: v1
kind: Secret
metadata:
  name: audit-webhook-kubeconfig
  namespace: clusters
type: Opaque
stringData:
  webhook-kubeconfig: |-
    apiVersion: v1
    clusters:
    - cluster:
        insecure-skip-tls-verify: true
        server: https://audit-webhook:8443
      name: cluster
    contexts:
    - context:
        cluster: cluster
        namespace: default
        user: admin
      name: admin
    current-context: admin
    kind: Config
    preferences: {}
    users:
    - name: admin
      user: {}
